services:
    admin.domains:
        class: AppBundle\Admin\DomainAdmin
        arguments:
            - ~
            - AppBundle\Entity\Domain
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Domains" }

    admin.languages:
        class: AppBundle\Admin\LanguageAdmin
        arguments:
            - ~
            - AppBundle\Entity\Language
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Languages" }

    admin.redirects:
        class: AppBundle\Admin\RedirectAdmin
        arguments:
            - ~
            - AppBundle\Entity\Redirect
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Redirects" }

    admin.site_pages:
        class: AppBundle\Admin\SitePageAdmin
        arguments:
            - ~
            - AppBundle\Entity\SitePage
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "SitePages" }

    admin.banners:
        class: AppBundle\Admin\BannerAdmin
        arguments:
            - ~
            - AppBundle\Entity\Banner
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banners" }

    admin.banner_order:
        class: AppBundle\Admin\BannerOrderAdmin
        arguments:
            - ~
            - AppBundle\Entity\BannerOrder
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banner orders" }

    admin.banner_place:
        class: AppBundle\Admin\BannerPlaceAdmin
        arguments:
            - ~
            - AppBundle\Entity\BannerPlace
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banner places" }

    admin.log:
        class: AppBundle\Admin\LogAdmin
        arguments:
            - ~
            - AppBundle\Entity\Log
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Logs", label: "Site logs" }

    admin.about_us:
        class: AppBundle\Admin\AboutUsAdmin
        arguments:
            - ~
            - AppBundle\Entity\AboutUs
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "About us" }

    admin.meta_tag:
        class: AppBundle\Admin\MetaTagAdmin
        arguments:
          - ~
          - AppBundle\Entity\MetaTag
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Meta tegs", label: "Meta tag name" }

    admin.meta_tag_content:
        class: AppBundle\Admin\MetaTagContentAdmin
        arguments:
          - ~
          - AppBundle\Entity\MetaTagContent
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Meta tegs", label: "Meta tag content", show_in_dashboard: true }

    admin.meta_tag_page:
        class: AppBundle\Admin\MetaTagPageAdmin
        arguments:
          - ~
          - AppBundle\Entity\MetaTagPage
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Meta tegs", label: "Meta tag page" }

    admin.news_category:
        class: AppBundle\Admin\NewsCategoryAdmin
        arguments:
          - ~
          - AppBundle\Entity\NewsCategory
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "News and Articles", label: "News categories" }

    admin.articles:
        class: AppBundle\Admin\ArticlesAdmin
        arguments:
          - ~
          - AppBundle\Entity\Articles
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "News and Articles", label: "Articles" }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments:
          - ~
          - AppBundle\Entity\User
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Site users", label: "Users" }

    admin.user_role:
        class: AppBundle\Admin\UserRoleAdmin
        arguments:
          - ~
          - AppBundle\Entity\UserRole
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Site users", label: "User roles" }

    admin.facebook:
        class: AppBundle\Admin\FacebookContentAdmin
        arguments:
          - ~
          - AppBundle\Entity\FacebookContent
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Social links", label: "Facebook" }

    admin.twitter:
        class: AppBundle\Admin\TwitterContentAdmin
        arguments:
          - ~
          - AppBundle\Entity\TwitterContent
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "Social links", label: "Twitter" }

    admin.world_news:
        class: AppBundle\Admin\WorldNewsAdmin
        arguments:
          - ~
          - AppBundle\Entity\WorldNews
          - ~
        tags:
          - { name: sonata.admin, manager_type: orm, group: "News and Articles", label: "World News" }








