services:
    admin.domains:
        class: AppBundle\Admin\DomainAdmin
        arguments:
            - ~
            - AppBundle\Entity\Domain
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Domains" }

    admin.languages:
        class: AppBundle\Admin\LanguageAdmin
        arguments:
            - ~
            - AppBundle\Entity\Language
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Languages" }

    admin.redirects:
        class: AppBundle\Admin\RedirectAdmin
        arguments:
            - ~
            - AppBundle\Entity\Redirect
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "Redirects" }

    admin.site_pages:
        class: AppBundle\Admin\SitePageAdmin
        arguments:
            - ~
            - AppBundle\Entity\SitePage
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Configurations", label: "SitePages" }

    admin.banners:
        class: AppBundle\Admin\BannerAdmin
        arguments:
            - ~
            - AppBundle\Entity\Banner
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banners" }

    admin.banner_order:
        class: AppBundle\Admin\BannerOrderAdmin
        arguments:
            - ~
            - AppBundle\Entity\BannerOrder
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banner orders" }

    admin.banner_place:
        class: AppBundle\Admin\BannerPlaceAdmin
        arguments:
            - ~
            - AppBundle\Entity\BannerPlace
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Site Banners", label: "Banner places" }












