fos_comment:
    db_driver: orm
    class:
        model:
            comment: AppBundle\Entity\Comments\Comment
            thread: AppBundle\Entity\Comments\Thread

#assetic:
#    bundles: [ "FOSCommentBundle" ]